import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../../Components/Header/Header";
import NavBar from "../../Components/NavBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Google Keep",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
